name: apiverve_didyoumean
description: Did You Mean is a simple tool for correcting spelling mistakes. It returns the corrected text.
version: 1.1.14
homepage: https://apiverve.com/marketplace/didyoumean?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/didyoumean-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
